### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ayaka14732** [BYVoid/ytenx#189]
```sh
>>> ./manage.py migrate --run-syncdb
...
>>> ./manage.py shell < ytenx/sync/import.py
CjengMuxPrengQim...
Done
CjengMuxNgixQim...
Done
CjengMux...
Done
YonhGheh...
Done
YonhMuxPrengQim...
Done
YonhMuxNgixQim...
Done
YonhMux...
Done
PrengQim...
Done
Dauh...
Done
NgixQim...
Done
PyanxTshet...
Done
KuangxYonhMiukTshiih...
Done
YonhMiuk...
Done
YonhMiukDzip...
Done
DrakDzuonDang...
Done
Cio...
Done
SieuxYonh...
Traceback (most recent call last):
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit
return self.connection.commit()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "./manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/home/ayaka/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/home/ayaka/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/ayaka/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
self.execute(*args, **cmd_options)
File "/home/ayaka/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
output = self.handle(*args, **options)
File "/home/ayaka/venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 92, in handle
exec(sys.stdin.read())
File "<string>", line 9, in <module>
File "/home/ayaka/ytenx/ytenx/sync/kyonh.py", line 46, in sync
syncSieuxYonh()
File "/home/ayaka/ytenx/ytenx/sync/kyonh.py", line 405, in syncSieuxYonh
traverse(base_path + 'SieuxYonh.txt', sync)
File "/home/ayaka/ytenx/ytenx/sync/common.py", line 13, in traverse
callback(line, num)
File "/home/ayaka/ytenx/ytenx/sync/kyonh.py", line 401, in sync
sieux.cio.add(cioMap[cio])
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 951, in add
self._add_items(
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/transaction.py", line 232, in __exit__
connection.commit()
File "/home/ayaka/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 267, in commit
self._commit()
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit
return self.connection.commit()
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/home/ayaka/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit
return self.connection.commit()
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by BYVoid** [comment]
Is the problem still there? I can't reproduce it.

**Comment by ayaka14732** [comment]
Yes, the problem is still there? I reproduced it on a different machine.

**Comment by ayaka14732** [comment]
Besides, the second command

```sh
./manage.py shell < ytenx/sync/import.py
```

ran for hours on Arch Linux, Python 3.9.
